name: WW2Blitz
options:
  bundleIdPrefix: com.cc
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    INFOPLIST_FILE: WW2Blitz/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: com.cc.ww2blitz
    MARKETING_VERSION: "1.0.4"
    CURRENT_PROJECT_VERSION: "1.0.4"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: ""

targets:
  WW2Blitz:
    type: application
    platform: iOS
    sources:
      - path: WW2Blitz/Sources
        type: group
      - path: WW2Blitz/LaunchScreen.storyboard
      - path: WW2Blitz/Resources
        type: folder
        buildPhase: resources
    settings:
      base:
        PRODUCT_NAME: WW2Blitz
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: WW2Blitz/Info.plist
      properties:
        UILaunchStoryboardName: LaunchScreen
        UIStatusBarHidden: true
        UIRequiresFullScreen: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        "UISupportedInterfaceOrientations~ipad":
          - UIInterfaceOrientationPortrait

schemes:
  WW2Blitz:
    build:
      targets:
        WW2Blitz: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
